services:
  postgres:
    image: postgres:17-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: jeevatix
      POSTGRES_USER: jeevatix
      POSTGRES_PASSWORD: jeevatix
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: