/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "AdminPortal": {
      "type": "sst.cloudflare.Worker"
      "url": string
    }
    "Api": {
      "type": "sst.cloudflare.Worker"
      "url": string
    }
    "BuyerPortal": {
      "type": "sst.cloudflare.Worker"
      "url": string
    }
    "ReservationCleanupCronHandler": {
      "type": "sst.cloudflare.Worker"
    }
    "ReservationCleanupQueue": {
      "type": "sst.cloudflare.Queue"
    }
    "SellerPortal": {
      "type": "sst.cloudflare.Worker"
      "url": string
    }
    "UploadsBucket": {
      "name": string
      "type": "sst.cloudflare.Bucket"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}