/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

import 'sst';
declare module 'sst' {
  export interface Resource {}
}
// cloudflare
import * as cloudflare from '@cloudflare/workers-types';
declare module 'sst' {
  export interface Resource {
    AdminPortal: cloudflare.Service;
    Api: cloudflare.Service;
    BuyerPortal: cloudflare.Service;
    ReservationCleanupCronHandler: cloudflare.Service;
    ReservationCleanupQueue: cloudflare.Queue;
    SellerPortal: cloudflare.Service;
    UploadsBucket: cloudflare.R2Bucket;
  }
}

import 'sst';
export {};
