"$schema" = "../../node_modules/wrangler/config-schema.json"
name = "jeevatix-api"
main = "src/index.ts"
compatibility_date = "2026-03-30"
compatibility_flags = ["nodejs_compat", "no_handle_cross_request_promise_resolution"]

[durable_objects]
bindings = [{ name = "TICKET_RESERVER", class_name = "TicketReserver" }]

[[migrations]]
tag = "v1"
new_classes = ["TicketReserver"]

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "jeevatix-uploads"

[[queues.producers]]
binding = "RESERVATION_CLEANUP_QUEUE"
queue = "reservation-cleanup"

[[queues.consumers]]
queue = "reservation-cleanup"
max_batch_size = 10
max_batch_timeout = 30

[triggers]
crons = ["* * * * *"]